site_name: GovHubBR
site_url: "https://govhub.github.io/govhub/"
site_author: Lab Livre
site_description: >-
  Gov Hub - plataforma livre de integração de dados e informações governamentais - Explore como a gestão orientada a dados pode transformar a administração pública, 
  integrando e qualificando dados de sistemas estruturantes essenciais. 
  Este projeto aborda os desafios da fragmentação e inconsistência de dados, promovendo eficiência, 
  transparência e melhor tomada de decisão no âmbito governamental.

# Repository
repo_name: GovHub-br/govhub
repo_url: https://github.com/GovHub-br/govhub

# Copyright
copyright: Lab Livre 2025

# Configuration
theme:
  name: material
  custom_dir: material/overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
  theme:
  language: pt-BR

# Plugins
plugins:
 # - blog
 # - search:
 #     separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
 # - minify:
 #     minify_html: true

# Hooks
hooks:
  - material/overrides/hooks/shortcodes.py
  - material/overrides/hooks/translations.py

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GovHub-br/govhub.githubio

extra_css:
  - assets/css/extra.css

  
# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - E-book:
    - Gov Hub - plataforma livre de integração de dados e informações governamentais: getting-started.md
  - Sobre o Projeto:
    - Propósito e Objetivo Geral: sobre-projeto/proposito-objetivo.md
    - Sistemas Estruturantes: sobre-projeto/sistemas-estruturantes.md
    - Gestão Orientada a Dados: sobre-projeto/gestao-dados.md
    - Conceitos: sobre-projeto/sistemas-estruturantes.md
    - Equipe: sobre-projeto/equipe.md
  - Getting started:
    - Instalação: getting-started.md
    - Guia de Novo usuario: guia-usuario.md
  - Replicação:
    - Visão Geral: replicacao/index.md
    - Pré-requisitos: replicacao/pre-requisitos.md
    - Arquitetura de Solução: replicacao/arquitetura.md
    - Integração de Dados: replicacao/integracao-dados.md
    - Dashboards e Templates: replicacao/dashboards-templates.md
  - Community:
    - Guia de Contribuição: contributing/guia-contribuicao.md
    - Tecnologias: contributing/tecnologias.md
    - Arquitetura do Projeto: contributing/arquitetura.md
    - Como importar um banco de dados de sistema estruturante: contributing/importar_bancos.md
    - Como Qualificar dados: contributing/qualificar.md
    - Como integrar bases de dados: contributing/integrar.md
    - Como gerar Dashboards: contributing/visualizar_dashboards.md
    - Melhores Praticas: contributing/praticas.md
    - Como implantar um Deploy: contributing/deploy.md
