name: App Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'airflow/**'
      - 'dbt/**'
      - 'jupyter/**'
      - 'superset/**'
      - 'requirements.txt'
      - 'Dockerfile'
  pull_request:
    branches: [ main ]
    paths:
      - 'airflow/**'
      - 'dbt/**'
      - 'jupyter/**'
      - 'superset/**'
      - 'requirements.txt'
      - 'Dockerfile'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov flake8

    - name: Run linting
      run: |
        # Only lint specific directories to avoid file not found errors
        flake8 src/govhub/ --count --max-complexity=10 --max-line-length=127 --statistics --extend-ignore=E203,W503

    - name: Run tests with coverage
      run: |
        pytest --cov=./ --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: false

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/govhub-app:latest
          ghcr.io/${{ github.repository }}/govhub-app:${{ github.sha }}
        cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/govhub-app:buildcache
        cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/govhub-app:buildcache,mode=max
