name: Check Changelog

on:
  pull_request:
    branches: [ main ]

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Check if CHANGELOG.md was modified
        id: check_changelog
        run: |
          if git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -q "CHANGELOG.md"; then
            echo "changelog_modified=true" >> $GITHUB_OUTPUT
          else
            echo "changelog_modified=false" >> $GITHUB_OUTPUT
          fi

      - name: Create comment if CHANGELOG.md wasn't modified
        if: steps.check_changelog.outputs.changelog_modified == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Lembrete: por favor, atualize o CHANGELOG.md com um resumo das suas alterações.'
            })
