name: CI/CD Application Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Lint with flake8
        run: |
          flake8 data_acquirer.py integrate_data_simple.py integrate_data_advanced.py process_siafi_large.py validate_fase2.py --max-line-length=88 --extend-ignore=E203,W503,E501
          
      - name: Format check with black
        run: |
          black --check --diff data_acquirer.py integrate_data_simple.py integrate_data_advanced.py process_siafi_large.py validate_fase2.py --line-length=88
          
      - name: Test with pytest
        run: |
          python -m py_compile data_acquirer.py
          python -m py_compile integrate_data_simple.py
          python -m py_compile integrate_data_advanced.py
          python -m py_compile process_siafi_large.py
          python -m py_compile validate_fase2.py
          python validate_fase2.py

  build-and-push:
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/gov-hub:latest
            ${{ secrets.DOCKER_USERNAME }}/gov-hub:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
